# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
tasks:
  - init: yarn dev
    command: yarn dev
ports:
  - port: 1234
    onOpen: open-preview
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
vscode:
  extensions:
    - wesbos.theme-cobalt2
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - redwan-hossain.auto-rename-tag-clone
    - aaron-bond.better-comments
    - dbaeumer.vscode-eslint
    - github.vscode-pull-request-github
    - editorconfig.editorconfig
    - eamodio.gitlens
    - redhat.vscode-yaml
    - pflannery.vscode-versionlens
    - svelte.svelte-vscode
    - pkief.material-icon-theme
    - glenn2223.live-sass
    - genuitecllc.codetogether